stages:
  - build-web
  - test-node
  - e2e-test

variables:
  ARTIFACTS_DIR: $CI_PROJECT_DIR/artifacts

services:
  - docker:dind

build-web:
  stage: build-web
  image: node:17
  variables:
    NODE_ENV: production
  script:
    - npm install yarn
    - yarn
    - yarn add webpack-cli
    - yarn build
  artifacts:
    paths:
      # /builds/gitlab-org/gitlab-foss/artifacts
      - $ARTIFACTS_DIR/dist
  cache:
    paths:
      - node_modules/
    policy: pull-push

e2e-test:
  stage: e2e-test
  image:
    name: docker/compose:1.24.0
    # needed in order to be able to run custom scripts
    entrypoint: [""]
  cache:
    paths:
      - node_modules/
  artifacts:
    paths:
      - $ARTIFACTS_DIR
  dependencies:
    - build-web
  script:
    - echo "Testing librimem e2e"
    - cp -r $ARTIFACTS_DIR/dist ./dist
    - docker-compose build
    - docker-compose up --abort-on-container-exit --exit-code-from cypress
