stages:
  - build
  - test
  - deploy_netlify
  - deploy_production

variables:
  name: Barakat

build:
  stage: build
  image: alpine
  variables:
    name: Orlando
  script:
    - echo "Building librimem"
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist
      # Our dependencies wont change that often
      - node_modules

test:
  stage: test
  image: alpine
  script:
    - echo "Testing librimem"

deploy_netlify:
  stage: deploy_netlify
  script:
    - echo "Deploying to netlify"
    - npm run deploy-netlify
    - echo "Deployed to netlify"
