stages:
  - build
  - test
  - deploy_netlify
  - deploy_production

variables:
  name: Barakat

build:
  stage: build
  image: node:17
  variables:
    name: Orlando
  environment:
    NODE_ENV: productionn
  script:
    - echo "Building librimem"
    - npm install
    - npm run build-ts
  artifacts:
    paths:
      - build
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths: node_modules
    policy: pull-push

test:
  stage: test
  image: node:17
  script:
    - echo "Testing librimem"
    # Run react-scripts tests
    - npm run test-react
    # Run unit tests with jest
    # - npm run test
  dependencies:
    - build

deploy_netlify:
  stage: deploy_netlify
  image: node:17
  script:
    - echo "Deploying to netlify"
    - npm run deploy-netlify
    - echo "Deployed to netlify"
