FROM node:17-alpine as build

WORKDIR /app

COPY . .

RUN npm install yarn

RUN yarn

RUN yarn add webpack-cli

RUN yarn build

FROM nginx:stable-alpine

COPY --from=build /app/dist /usr/share/nginx/html
COPY --from=build /app/nginx/nginx-ci.conf /etc/nginx/conf.d/default.conf

EXPOSE 8067

ENTRYPOINT [ "nginx", "-g", "daemon off"]
