apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      component: frontend
  template:
    metadata:
      labels:
        component: frontend
    spec:
      containers:
        - name: lm-frontend
          image: josemagne/lm-frontend:1.0.0
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_PORT
              value: "4000"
            - name: BACKEND_IP_PRODUCTION
              value: books-cluster-ip-service
      imagePullSecrets:
        - name: dockersecret
