name: lm cicd

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu:latest

  steps:
    - uses: actions/checkout@v2
    - name: use node.js
    - uses: actions/setup-node@2
    - name: build
    - run: |
        npm ci
        npm run build
        npm test
