name: lm cicd

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: build lm
    runs-on: ubuntu-20.04

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: use node.js
        uses: actions/setup-node@v2
      - run: |
          npm install yarn
          yarn
          npm run build
          # npm run test
          npm run deploy-netlify
