name: lm cicd

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-netlify:
    name: build lm
    runs-on: ubuntu-20.04

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: use node.js
        uses: actions/setup-node@v2
      - run: |
          npm install yarn
          yarn
          npm run build-ts
          npm run build
          # npm run test
          npx netlify deploy --auth ${{secrets.NETLIFY}} --build --dir dist --prod --site librimem

  build-and-deploy:
    name: build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: josemagne
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
      - name: Docker Build and Push, Kubernetes apply
        run: |
          docker build --tag josemagne/lm-frontend:1.0.3 .
          docker push josemagne/lm-frontend:1.0.3
          export DOCKER_CONFIG=$(cat ~/.docker/config.json | base64 -w 0)
          sed -i'' -e "s/DOCKER_CONFIG/$DOCKER_CONFIG/g" infrastructure/k8s/dockersecret.yaml
          kubectl apply -f infrastructure/k8s/books-depl.yaml
