name: Run Cypress Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    # Cypress Docker image with Chrome v91
    # and Firefox v89 pre-installed
    container: cypress/base
    steps:
      - uses: actions/checkout@v2

      - name: Cypress tests
        uses: cypress-io/github-action@v3.0.0
        with:
          browser: electron
          start: npm run ci:start-server

      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
